name       : apitrace
version    : '9.0'
release    : 4
source     :
    - https://github.com/apitrace/apitrace/archive/9.0.tar.gz : 0eec81ba7d3799622336319785465a2982a0621898842517a07894d7e2aa18eb
license    : MIT
component  : programming.tools
homepage   : https://apitrace.github.io/
summary    : Tools for tracing OpenGL, Direct3D, and other graphics APIs
description: |
    Tools for tracing OpenGL, Direct3D, and other graphics APIs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libpng)
    - pkgconfig(libprocps)
    - pkgconfig(x11)
rundeps    :
    - python-pillow
setup      : |
    %cmake_ninja -DENABLE_SSE42=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/apitrace.desktop $installdir/usr/share/applications/apitrace.desktop
