name       : apitrace
version    : '8.0'
release    : 2
source     :
    - https://github.com/apitrace/apitrace/archive/8.0.tar.gz : 45f61fb4859606ee54ebfd7dd8a4dedce18b9fe8a2523bbd23526bd9413b6b6c
license    : MIT
component  : programming.tools
summary    : Tools for tracing OpenGL, Direct3D, and other graphics APIs
description: |
    Tools for tracing OpenGL, Direct3D, and other graphics APIs.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libprocps)
    - pkgconfig(Qt5Core)
rundeps    :
    - python-pillow
setup      : |
    %cmake_ninja -DENABLE_SSE42=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/apitrace.desktop $installdir/usr/share/applications/apitrace.desktop
