name       : apitrace
version    : '11.1'
release    : 8
source     :
    - git|https://github.com/apitrace/apitrace.git : 11.1
license    : MIT
component  : programming.tools
homepage   : https://apitrace.github.io/
summary    : Tools for tracing OpenGL, Direct3D, and other graphics APIs
description: |
    Tools for tracing OpenGL, Direct3D, and other graphics APIs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libbrotlidec)
    - pkgconfig(libpng)
    - pkgconfig(libprocps)
    - pkgconfig(x11)
rundeps    :
    - python-pillow
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/apitrace.desktop $installdir/usr/share/applications/apitrace.desktop
