name       : apitrace
version    : 7.1
release    : 1
source     :
    - https://github.com/apitrace/apitrace/archive/7.1.tar.gz : 2103386d747d34f3d6fb1d01fde9078a45ad2e9976afab3a7489c95b08dde0a2
license    : MIT
component  : programming.tools
summary    : Tools for tracing OpenGL, Direct3D, and other graphics APIs
description: |
    Tools for tracing OpenGL, Direct3D, and other graphics APIs
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpng)
    - pkgconfig(libprocps)
    - pkgconfig(python3)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKitWidgets)
    - python-pillow-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/apitrace.desktop $installdir/usr/share/applications/apitrace.desktop