name       : apitrace
version    : '10.0'
release    : 7
source     :
    - https://github.com/apitrace/apitrace/archive/refs/tags/10.0.tar.gz : 2e57d37af39369d7ce78666acb8afb1a49ec758f683a21077ec39eb0befae4ad
license    : MIT
component  : programming.tools
homepage   : https://apitrace.github.io/
summary    : Tools for tracing OpenGL, Direct3D, and other graphics APIs
description: |
    Tools for tracing OpenGL, Direct3D, and other graphics APIs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libpng)
    - pkgconfig(libprocps)
    - pkgconfig(x11)
rundeps    :
    - python-pillow
setup      : |
    %patch -p1 < $pkgfiles/removed_glibc_private_symbols.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/apitrace.desktop $installdir/usr/share/applications/apitrace.desktop
